from datetime import date

from sqlalchemy.orm import Session

from app.models.patient import Patient
from app.models.note import Note

PATIENTS = [
    {
        "first_name": "John",
        "last_name": "Doe",
        "dob": date(1968, 5, 14),
        "email": "john.doe@email.com",
        "phone": "555-0101",
        "address": "123 Oak St, Springfield, IL",
        "blood_type": "O+",
        "allergies": "Penicillin",
        "conditions": "Hypertension, Type 2 Diabetes",
        "status": "Active",
        "last_visit": date(2026, 3, 18),
    },
    {
        "first_name": "Sarah",
        "last_name": "Chen",
        "dob": date(1985, 11, 2),
        "email": "sarah.chen@email.com",
        "phone": "555-0102",
        "address": "456 Maple Ave, Portland, OR",
        "blood_type": "A-",
        "allergies": "Sulfa drugs, Latex",
        "conditions": "Asthma",
        "status": "Active",
        "last_visit": date(2026, 3, 25),
    },
    {
        "first_name": "Marcus",
        "last_name": "Williams",
        "dob": date(1972, 8, 20),
        "email": "m.williams@email.com",
        "phone": "555-0103",
        "address": "789 Pine Rd, Austin, TX",
        "blood_type": "B+",
        "allergies": "",
        "conditions": "GERD, Hyperlipidemia",
        "status": "Follow-up",
        "last_visit": date(2026, 3, 10),
    },
    {
        "first_name": "Emily",
        "last_name": "Rodriguez",
        "dob": date(1990, 3, 15),
        "email": "e.rodriguez@email.com",
        "phone": "555-0104",
        "address": "321 Elm St, Denver, CO",
        "blood_type": "AB+",
        "allergies": "Aspirin",
        "conditions": "Anxiety, Migraine",
        "status": "Active",
        "last_visit": date(2026, 3, 28),
    },
    {
        "first_name": "David",
        "last_name": "Kim",
        "dob": date(1955, 12, 1),
        "email": "d.kim@email.com",
        "phone": "555-0105",
        "address": "654 Birch Ln, Seattle, WA",
        "blood_type": "A+",
        "allergies": "Codeine",
        "conditions": "Atrial Fibrillation, Osteoarthritis",
        "status": "Follow-up",
        "last_visit": date(2026, 2, 28),
    },
    {
        "first_name": "Lisa",
        "last_name": "Patel",
        "dob": date(1988, 7, 22),
        "email": "l.patel@email.com",
        "phone": "555-0106",
        "address": "987 Cedar Dr, Miami, FL",
        "blood_type": "O-",
        "allergies": "",
        "conditions": "Hypothyroidism",
        "status": "Active",
        "last_visit": date(2026, 3, 20),
    },
    {
        "first_name": "Robert",
        "last_name": "Johnson",
        "dob": date(1960, 1, 30),
        "email": "r.johnson@email.com",
        "phone": "555-0107",
        "address": "147 Walnut St, Chicago, IL",
        "blood_type": "B-",
        "allergies": "NSAIDs, Iodine",
        "conditions": "COPD, Coronary Artery Disease",
        "status": "Active",
        "last_visit": date(2026, 3, 15),
    },
    {
        "first_name": "Maria",
        "last_name": "Garcia",
        "dob": date(1995, 9, 8),
        "email": "m.garcia@email.com",
        "phone": "555-0108",
        "address": "258 Spruce Ct, Phoenix, AZ",
        "blood_type": "AB-",
        "allergies": "Amoxicillin",
        "conditions": "Iron Deficiency Anemia",
        "status": "Inactive",
        "last_visit": date(2025, 12, 5),
    },
    {
        "first_name": "James",
        "last_name": "Thompson",
        "dob": date(1978, 4, 12),
        "email": "j.thompson@email.com",
        "phone": "555-0109",
        "address": "369 Ash Blvd, Nashville, TN",
        "blood_type": "O+",
        "allergies": "",
        "conditions": "Lower Back Pain, Insomnia",
        "status": "Active",
        "last_visit": date(2026, 3, 22),
    },
    {
        "first_name": "Jennifer",
        "last_name": "Lee",
        "dob": date(1982, 6, 5),
        "email": "j.lee@email.com",
        "phone": "555-0110",
        "address": "741 Poplar Way, Boston, MA",
        "blood_type": "A+",
        "allergies": "Morphine",
        "conditions": "Rheumatoid Arthritis",
        "status": "Follow-up",
        "last_visit": date(2026, 3, 5),
    },
    {
        "first_name": "Michael",
        "last_name": "Brown",
        "dob": date(1963, 10, 18),
        "email": "m.brown@email.com",
        "phone": "555-0111",
        "address": "852 Hickory Rd, Atlanta, GA",
        "blood_type": "B+",
        "allergies": "Erythromycin",
        "conditions": "Type 1 Diabetes, Neuropathy",
        "status": "Active",
        "last_visit": date(2026, 3, 30),
    },
    {
        "first_name": "Amanda",
        "last_name": "Wilson",
        "dob": date(1992, 2, 25),
        "email": "a.wilson@email.com",
        "phone": "555-0112",
        "address": "963 Magnolia St, San Diego, CA",
        "blood_type": "O+",
        "allergies": "",
        "conditions": "PCOS, Depression",
        "status": "Active",
        "last_visit": date(2026, 3, 12),
    },
    {
        "first_name": "Kevin",
        "last_name": "Nguyen",
        "dob": date(1980, 3, 9),
        "email": "k.nguyen@email.com",
        "phone": "555-0113",
        "address": "114 Juniper St, Houston, TX",
        "blood_type": "A-",
        "allergies": "Shellfish",
        "conditions": "Chronic Kidney Disease Stage 2",
        "status": "Active",
        "last_visit": date(2026, 3, 27),
    },
    {
        "first_name": "Rachel",
        "last_name": "Adams",
        "dob": date(1975, 6, 18),
        "email": "r.adams@email.com",
        "phone": "555-0114",
        "address": "502 Sycamore Dr, Charlotte, NC",
        "blood_type": "O+",
        "allergies": "Tetracycline",
        "conditions": "Fibromyalgia, Irritable Bowel Syndrome",
        "status": "Follow-up",
        "last_visit": date(2026, 3, 8),
    },
    {
        "first_name": "Thomas",
        "last_name": "Wright",
        "dob": date(1950, 11, 25),
        "email": "t.wright@email.com",
        "phone": "555-0115",
        "address": "830 Chestnut Ave, Philadelphia, PA",
        "blood_type": "B-",
        "allergies": "Sulfonamides, Contrast dye",
        "conditions": "Congestive Heart Failure, Chronic Kidney Disease Stage 3",
        "status": "Active",
        "last_visit": date(2026, 3, 29),
    },
    {
        "first_name": "Olivia",
        "last_name": "Martinez",
        "dob": date(1998, 1, 3),
        "email": "o.martinez@email.com",
        "phone": "555-0116",
        "address": "215 Willow Ct, San Antonio, TX",
        "blood_type": "AB+",
        "allergies": "",
        "conditions": "Generalized Anxiety Disorder",
        "status": "Active",
        "last_visit": date(2026, 3, 19),
    },
    {
        "first_name": "William",
        "last_name": "Taylor",
        "dob": date(1966, 7, 14),
        "email": "w.taylor@email.com",
        "phone": "555-0117",
        "address": "608 Redwood Blvd, Minneapolis, MN",
        "blood_type": "A+",
        "allergies": "Cephalosporins",
        "conditions": "Parkinson's Disease",
        "status": "Active",
        "last_visit": date(2026, 3, 14),
    },
    {
        "first_name": "Sophia",
        "last_name": "Anderson",
        "dob": date(1993, 4, 30),
        "email": "s.anderson@email.com",
        "phone": "555-0118",
        "address": "441 Dogwood Ln, Raleigh, NC",
        "blood_type": "O-",
        "allergies": "",
        "conditions": "Celiac Disease",
        "status": "Inactive",
        "last_visit": date(2025, 11, 20),
    },
    {
        "first_name": "Daniel",
        "last_name": "Harris",
        "dob": date(1970, 9, 11),
        "email": "d.harris@email.com",
        "phone": "555-0119",
        "address": "772 Cypress Rd, Las Vegas, NV",
        "blood_type": "B+",
        "allergies": "Metformin",
        "conditions": "Gout, Hypertension",
        "status": "Follow-up",
        "last_visit": date(2026, 3, 2),
    },
    {
        "first_name": "Grace",
        "last_name": "Robinson",
        "dob": date(1987, 12, 19),
        "email": "g.robinson@email.com",
        "phone": "555-0120",
        "address": "339 Laurel St, Columbus, OH",
        "blood_type": "A+",
        "allergies": "Bee stings, Peanuts",
        "conditions": "Epilepsy",
        "status": "Active",
        "last_visit": date(2026, 3, 24),
    },
]

NOTES = [
    (1, "Patient reports intermittent dizziness over the past two weeks. Blood pressure elevated at 145/92. Adjusting Lisinopril dosage."),
    (1, "Follow-up on medication change. BP improved to 130/85. Patient reports fewer dizzy spells. Continue current regimen."),
    (1, "HbA1c at 7.2%, slight improvement. Reinforced dietary guidelines. Medication adherence has been good."),
    (2, "Routine asthma check. Peak flow readings stable. Inhaler technique reviewed and corrected. No exacerbations this quarter."),
    (2, "Patient reports increased wheezing with seasonal changes. Added Montelukast to regimen. Allergy testing recommended."),
    (3, "Endoscopy results show mild esophagitis. Continuing PPI therapy. Advised dietary modifications — avoid spicy foods, caffeine."),
    (3, "Lipid panel: LDL 158, HDL 42. Starting Atorvastatin 20mg. Discussed exercise plan and dietary changes."),
    (4, "Patient reports 3-4 migraines per month, impacting work. Starting Sumatriptan for acute episodes. Headache diary requested."),
    (4, "Anxiety well-managed with current SSRI. PHQ-9 score: 6. No suicidal ideation. Continue current management."),
    (5, "INR at 2.4, within range. Warfarin dose unchanged. Patient tolerable of current AF management. Echo scheduled for next visit."),
    (5, "Knee X-ray shows moderate OA bilateral. Referred to physical therapy. Trial of Diclofenac gel for pain management."),
    (6, "TSH normalized at 3.1 on Levothyroxine 75mcg. Patient reports improved energy. Continue current dose, recheck in 6 months."),
    (7, "Spirometry shows FEV1 at 62% predicted. Adjusted bronchodilator regimen. Smoking cessation counseling provided again."),
    (7, "Cardiac stress test negative for ischemia. Continue current medications. Cholesterol panel next visit."),
    (9, "MRI lumbar spine: L4-L5 disc bulge, no nerve impingement. Referred to physical therapy. Avoid heavy lifting."),
    (9, "Sleep study results: mild obstructive sleep apnea. CPAP trial initiated. Follow-up in 4 weeks."),
    (10, "RA flare — swelling in bilateral hands. CRP elevated at 12. Prednisone burst prescribed. Rheumatology referral made."),
    (11, "Continuous glucose monitoring review. Time in range: 68%. Adjusting insulin pump basal rates. Neuropathy screening normal."),
    (12, "Metformin started for insulin resistance related to PCOS. Discussed lifestyle modifications. Mood stable on Sertraline."),
    (13, "Creatinine stable at 1.4. eGFR 62. Continuing ACE inhibitor. Renal diet reviewed. Labs again in 3 months."),
    (14, "Fibromyalgia pain worsening with weather changes. Trigger point assessment performed. Duloxetine dose increased to 60mg."),
    (14, "IBS flare — increased bloating and abdominal discomfort. Low FODMAP diet discussed. Referral to GI nutritionist."),
    (15, "BNP at 320, up from 280 last visit. Furosemide increased. Daily weight monitoring reinforced. Fluid restriction to 1.5L."),
    (15, "Renal function declining — eGFR 38. Nephrology co-management in place. Potassium 5.1, adjusting medications."),
    (16, "PHQ-9 score improved to 4 from 8 with CBT + Buspirone. Patient coping well with school stress. Continue current plan."),
    (17, "Tremor assessment: slight progression. Carbidopa-Levodopa timing adjusted. Occupational therapy referral for fine motor tasks."),
    (18, "Annual celiac follow-up. tTG-IgA negative, good dietary compliance. Vitamin D and iron levels within normal limits."),
    (19, "Acute gout flare in right first MTP. Colchicine started. Uric acid at 9.2. Allopurinol to begin after flare resolves."),
    (19, "BP 152/94 despite Amlodipine. Adding Hydrochlorothiazide 25mg. 24-hour ambulatory BP monitoring ordered."),
    (20, "Seizure-free for 14 months on Levetiracetam. EEG shows improvement. No dose changes. Driving clearance discussed."),
    (20, "Epipen prescription renewed. Allergy action plan updated. Patient carries auto-injector at all times."),
]


def seed_database(db: Session) -> None:
    existing = db.query(Patient).count()
    if existing > 0:
        return

    patients = []
    for data in PATIENTS:
        patient = Patient(**data)
        db.add(patient)
        patients.append(patient)

    db.flush()

    for patient_idx, content in NOTES:
        note = Note(
            patient_id=patients[patient_idx - 1].id,
            content=content,
        )
        db.add(note)

    db.commit()
    print(f"Seeded {len(patients)} patients and {len(NOTES)} notes.")
